### ISSUE TITLE
Module is broken after Mojolicious 8.24

### ISSUE THREAD

**Issue by jonisno** [garu/MojoX-Log-Log4perl#5]
Mojolicious 8.24 breaks MojoX::Log::Log4perl

```
Mojo::Reactor::EV: I/O watcher failed: Can't locate object method "context" via package "MojoX::Log::Log4perl" at /Users/jonis/.plenv/versions/5.26.2/lib/perl5/site_perl/5.26.2/Mojolicious/Plugin/DefaultHelpers.pm line 175.
```

**Comment by garu** [comment]
@jonisno Thank you for the report, and thank you @schobes for providing the workaround. I have modified it a bit so it returns the object itself, being a little more compatible to `context()`s proposed usage. MojoX::Log::Log4perl version 0.12 should be hitting your nearest cpan mirror anytime now!
